name: automatic document generation by doxygen

on:
  push:
    branches:
      - develop

jobs:
  doxygen:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: docs

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.5

      - name: Git config, commit, and push. 
        run: |
          git config --local user.email "okano.development@gmail.com"
          git config --local user.name "okano-tomoyuki"
          git pull
          git add .
          git commit -m "add action #"$(echo ${GITHUB_SHA::7})
          git push origin docs